// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: orca2/getuser.proto

package proto3

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StatusUpdaterClient is the client API for StatusUpdater service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatusUpdaterClient interface {
	GetUser(ctx context.Context, in *ValidUserName, opts ...grpc.CallOption) (*StatusTwo, error)
}

type statusUpdaterClient struct {
	cc grpc.ClientConnInterface
}

func NewStatusUpdaterClient(cc grpc.ClientConnInterface) StatusUpdaterClient {
	return &statusUpdaterClient{cc}
}

func (c *statusUpdaterClient) GetUser(ctx context.Context, in *ValidUserName, opts ...grpc.CallOption) (*StatusTwo, error) {
	out := new(StatusTwo)
	err := c.cc.Invoke(ctx, "/proto.StatusUpdater/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatusUpdaterServer is the server API for StatusUpdater service.
// All implementations must embed UnimplementedStatusUpdaterServer
// for forward compatibility
type StatusUpdaterServer interface {
	GetUser(context.Context, *ValidUserName) (*StatusTwo, error)
	mustEmbedUnimplementedStatusUpdaterServer()
}

// UnimplementedStatusUpdaterServer must be embedded to have forward compatible implementations.
type UnimplementedStatusUpdaterServer struct {
}

func (UnimplementedStatusUpdaterServer) GetUser(context.Context, *ValidUserName) (*StatusTwo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedStatusUpdaterServer) mustEmbedUnimplementedStatusUpdaterServer() {}

// UnsafeStatusUpdaterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatusUpdaterServer will
// result in compilation errors.
type UnsafeStatusUpdaterServer interface {
	mustEmbedUnimplementedStatusUpdaterServer()
}

func RegisterStatusUpdaterServer(s grpc.ServiceRegistrar, srv StatusUpdaterServer) {
	s.RegisterService(&StatusUpdater_ServiceDesc, srv)
}

func _StatusUpdater_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidUserName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusUpdaterServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StatusUpdater/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusUpdaterServer).GetUser(ctx, req.(*ValidUserName))
	}
	return interceptor(ctx, in, info, handler)
}

// StatusUpdater_ServiceDesc is the grpc.ServiceDesc for StatusUpdater service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatusUpdater_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StatusUpdater",
	HandlerType: (*StatusUpdaterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _StatusUpdater_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orca2/getuser.proto",
}
